### ISSUE TITLE
 Investigate if Selenium and/or Playwright support allowing to share webcams

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/bbb-network-cam-integration#2]
We aren't sure if [Selenium](https://www.selenium.dev/) or [Playwright](https://playwright.dev/) support allowing webcam sharing. Investigate if they can. Choose the framework that seems to support this. Choose whatever you like if they both support this.

If neither supports this, start a conversation about workarounds.

**Comment by arschreiber** [comment]
As described [here](https://testingbot.com/support/selenium/permission-popups), selenium supports granting webcam permission, e.g., by setting the option "--use-fake-ui-for-media-stream".
