### ISSUE TITLE
Don't return `None` to return `None`

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/bbb-network-cam-integration#23]
If you don't return anything, you already return `None` in Python. Having `return None` at the end is therefore superflous.
For example, here you can just omit `return None`:

https://github.com/elan-ev/bbb-network-cam-integration/blob/89cb9a054002de71df9175c11db8f7ed3d30da10/cam_supervisor.py#L50-L55

Example to shoe that you still get `None` without it:

```py
>>> def a(b):
...     if b:
...         return 123
... 
>>> a(0) is None
True
```

**Comment by arschreiber** [comment]
Citing PEP 8:
"Be consistent in return statements. Either all return statements in a function should return an expression, or none of them should. **If any return statement returns an expression,** any return statements where no value is returned should explicitly state this as return None, and **an explicit return statement should be present at the end of the function (if reachable).**"

So it seems that in this case, the explicit return statement is the better choice according to PEP 8.
