### ISSUE TITLE
Use Private Chat to Control Camera - Mute/Unmute

### ISSUE THREAD

**Issue by tibroc** [elan-ev/bbb-network-cam-integration#35]
There are a couple of use cases where you would like to manipulate the camera stream. E.g. muting/unmuting the Microphone.
One possible way to interact with the camera could be to use the private Chat for that. We should do a prototype for that.

- start a private Chat with the camera user
- listen only to moderators, as only they should be able to manipulate the camera
- mute/unmute the camera with a command (e.g. slash commands, like `/mute`, `/unmute` or `/togglemic`)

**Comment by lkiesow** [comment]
I don't think `/togglemic` is very useful. I cannot come up with a situation where I don't know what state I want to set the muted state to. Did you have something in mind?
